server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/librarysolo
    username: postgres
    password: 123asd,./
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      format-sql: true
      
libdirector:
  app:
   jwtSecret: libraryotobot@12    
   jwtExpirationMs: 86400000
   
   
logging:
 file:
  name: logs/libdirector.log
 pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
    
 level:
  '[org.springframework.web]': ERROR
  '[org.hibernate]': ERROR
  '[libdirector]': ERROR
    
info:
  application:
   name: 'Bibliotheksverwaltungsprogramm'
   description: 'Das Bibliotheksverwaltungsprogramm.Es ist programmieret man mit Java-SpringBoot'
   version: '@project.version@' 
    
  