server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

##spring:
  ##datasource:
    ##url: jdbc:postgresql://localhost:5432/librarysolo
    ##username: postgres
    ##password: 123asd,./
    ##driver-class-name: org.postgresql.Driver



      ##
      ### jpa:
      ##  show-sql: true
      ## database-platform: org.hibernate.dialect.PostgreSQLDialect
      ##hibernate:
      ##ddl-auto: update
      ##properties:
    ## format-sql: true



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/librarysolo
    username: root
    password: asd123,./
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      '[hibernate.format_sql]': true

      
libdirector:
  app:
   jwtSecret: libid@12
   jwtExpirationMs: 86400000
   
   
logging:
 file:
  name: logs/libdirector.log
 pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
    
 level:
  '[org.springframework.web]': ERROR
  '[org.hibernate]': ERROR
  '[libdirector]': ERROR
    
info:
  application:
   name: 'Bibliotheksverwaltungsprogramm'
   description: 'Das Bibliotheksverwaltungsprogramm.Es ist programmieret man mit Java-SpringBoot'
   version: '@project.version@' 
    
  